config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tasks

  # # read all tasks
  # get 'tasks' => 'tasks#index'
  # # read a specific task
  # get 'tasks/:id' => 'tasks#show'
  # # create a new task
  # get 'tasks/new' => 'tasks#new'
  # post 'tasks' => 'tasks#create'
  # # update a task
  # get 'tasks/:id/edit' => 'tasks#edit'
  # patch 'tasks/:id' => 'tasks#update'
  # # destroy a task
  # delete 'tasks/:id' => 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def create
    task = Task.create(task_params)
    redirect_to task_path(task)
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :done, :description, :priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :name, "name" %>
  <%= f.text_field :name %>

  <%= f.label :done, "done" %>
  <%= f.check_box :done %>

  <%= f.label :description, "description" %>
  <%= f.text_field :description %>

  <%= f.label :priority, "priority" %>
  <%= f.number_field :priority %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>TO DO</h1>

<% @tasks.each do |task| %>
  <h3><%= task.name %></h3>
  <p>done: <%= task.done %></p>
  <%= link_to "check task details", task_path(task)%>
  <%= link_to "delete task", task_path(task), method: :delete %>
  <p>**************************</p>
<% end %>
<%= link_to "create a new task", new_task_path %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :name, "name" %>
  <%= f.text_field :name %>

  <%= f.label :description, "description" %>
  <%= f.text_field :description %>

  <%= f.label :priority, "priority" %>
  <%= f.number_field :priority %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p>done: <%= @task.done %></p>
<p>description: <%= @task.description %></p>
<p>priority: <%= @task.priority %></p>
<p>Go back to: <%= link_to "TO DO", tasks_path %></p>